### ISSUE TITLE
After following the tutorial, no tree shown

### ISSUE THREAD

**Issue by disadone** [aaronmck/SC_GESTALT#1]
I follow the example shown before the "Adjust the existing scripts for your data" section.
No lineage tree is shown.

![sc-](https://user-images.githubusercontent.com/13982373/69523052-d9686100-0f9d-11ea-8d85-b272144cb528.png)

Thank you.

**Comment by aaronmck** [comment]
Hi disadone,

The trees are not automatically generated in this pipeline. This repository was frozen with the initial paper, and on-going work is being done here: https://github.com/mckennalab/SingleCellLineage

That repository might better serve your needs. Best,
Aaron
