### ISSUE TITLE
no Maul.jar file in docker

### ISSUE THREAD

**Issue by disadone** [aaronmck/SC_GESTALT#2]
/app/bin/ does not have Maul.jar while barcode is not NA

**Comment by disadone** [comment]
The Maul.jar downlaod path in Docker file pulled from hub.docker.com is broken
The link is [Maul.jar](https://github.com/aaronmck/Maul/releases)

**Comment by aaronmck** [comment]
Hi disadone,

Again this repository was simply to freeze the code used to generate Bushra's paper and doesn't contain all aspects of the processing pipeline (only those that were used in that paper).  The repository https://github.com/mckennalab/SingleCellLineage contains more of the ongoing code for our lineage barcodes. I'll add a note at the top of the README about this.

Aaron

**Comment by disadone** [comment]
Thank you! Aaron.
